-----------------------------------------
-- LOCALIZED GLOBAL VARIABLES
-----------------------------------------

EMPTY_STRING = ""
LEFT_MOUSE_BUTTON = 1
RIGHT_MOUSE_BUTTON = 2
MIDDLE_MOUSE_BUTTON = 3

Enums = {
	AlikrMap = 5,
	ApocryphaMap = 50,
	ArtaeumMap = 33,
	AuridonMap = 15,
	AzkthzandCavernMap = 41,
	BalfieraMap = 24,
	BalFoyenMap = 18,
	BangkoraiMap = 6,
	BetnikhMap = 20,
	Blackwood = 43,
	BleakrockIsleMap = 22,
	ClockworkCityMap = 31,
	ColdharbourMap = 23,
	CraglornMap = 25,
	CyrodiilMap = 14,
	DeshaanMap = 10,
	EastmarchMap = 13,
	Eyevea = 52,
	FargraveMap = 47,
	GalenMap = 48,
	GlenumbraMap = 2,
	GoldCoastMap = 29,
	GrahtwoodMap = 7,
	GreenshadeMap = 16,
	GreymoorCaverns = 39,
	KhenarthisRoostMap = 21,
	HewsBaneMap = 28,
	HighIsleMap = 46,
	ImperialCityMap = 26,
	MalabalTorMap = 8,
	MurkmireMap = 34,
	NorgTzelMap = 35,
	NorthernElsweyrMap = 36,
	ReapersMarchMap = 17,
	RivenspireMap = 3,
	ShadowfenMap = 9,
	SolsticeMap = 53,
	SouthernElsweyrMap = 37,
	StonefallsMap = 11,
	StormhaveMap = 4,
	StrosMKaiMap = 19,
	SummersetMap = 32,
	TelvanniPeninsulaMap = 49,
	TheDeadlandsMap = 45,
	TheReachMap = 42,
	TheRiftMap = 12,
	VvardenfellMap = 30,
	WesternSkyrimMap = 38,
	WestWealdMap = 51,
	WrothgarMap = 27,
}
