-----------------------------------------
-- LOCALIZED GLOBAL VARIABLES
-----------------------------------------

local ZGV = _G.ZGV
local Data = {}
local Travel

-----------------------------------------
-- SAVED REFERENCES
-----------------------------------------

Travel = ZGV.Travel
Travel.Data = Data

-----------------------------------------
-- MAP DATA
-----------------------------------------

--[[
	\s*(\[.*\]) = ([0-9]*),\n  	->	\t\1 = \2,\n
	\t(\[.*\]) = ([0-9]*)		->	\t\2##\1 = \2
	\t[0-9]*##			->	\t
--]]


Data.MapIdsByName = {

	-- Aldmeri Dominion
	-- Khenarthi's Roost
	["Khenarthi's Roost"]                   =   1,
	["Temple of the Mourning Spring"]       =   2,
	["Hazak's Lair"]                        =   3,
	["Shattered Shoals"]                    =   4,
	["The Mangroves"]                       =   5,
	["Mistral"]                             =   6,
	["Cat's Eye Quay"]                      =   7,
	
	-- Auridon
	["Vulkhel Guard"]                       =   8,
	["Vulkhel Guard Outlaws Refuge"]        =   9,
	["Auridon"]                             =  10,
	["Del's Claim"]                         =  11,
	["Ondil"]                               =  12,
	["Phaer Catacombs"]                     =  13,
	["Inner Tanzelwil"]                     =  14,
	["Tower of the Vale - Temple"]          =  15,
	["Tower of the Vale - Rage"]            =  16,
	["Tower of the Vale - Bliss"]           =  17,
	["Tower of the Vale - Bliss Top"]       =  18,
	["Tower of the Vale - Despair"]         =  19,
	["Entila's Folly"]                      =  20,
	["Smugglerstunnel"]                     =  21,
	["Skywatch"]                            =  22,
	["The Veiled Keep"]                     =  23,
	["Ezduiin Undercroft"]                  =  24,
	["Wansalen"]                            =  25,
	["Quendeluun South Ruins"]              =  26,
	["Abandoned Mine"]                      =  27,
	["Bewan"]                               =  28,
	["Saltspray Cave"]                      =  29,
	["Torinaan Shrine"]                     =  30,
	["Mehrunes' Spite"]                     =  31,
	["The Vault of Exile"]                  =  32,
	["Firsthold"]                           =  33,
	["The Refuge of Dread"]                 =  34,
		
	-- Grahtwood
	["Haven"]                               =  35,
	["Haven Sewers"]                        =  36,
	["Grahtwood"]                           =  37,
	["Sacred Leap Grotto"]                  =  38,
	["The Scuttle Pit"]                     =  39,
	["Brackenleaf"]                         =  40,
	["Elden Root"]                          =  41,
	["Elden Root Mages Guild"]              =  42,
	["Elden Root Throne Room"]              =  43,
	["Elden Root Fighters Guild"]           =  44,
	["Elden Root Outlaws Refuge"]           =  45,
	["Cave of Broken Sails"]                =  46,
	["Gray Mire"]                           =  47,
	["Bone Orchard"]                        =  48,
	["Cathedral of the Golden Path"]        =  49,
	["Ne Salas"]                            =  50,
	["Mobar Mine"]                          =  51,
	["The Middens"]                         =  52,
	["Vinedeath Cave"]                      =  53,
	["Ossuary of Telacar"]                  =  54,
	["Laeloria Ruins"]                      =  55,
	["Karthdar"]                            =  56,
	["Cormount Prison"]                     =  57,
	["Reliquary Ruins"]                     =  58,
	["Reliquary Vault"]                     =  59,
	["Ancient Cave"]                        =  60,
	["Faltonia's Mine"]                     =  61,
	["Barkbite Cave"]                       =  62,
	["Barkbite Mine"]                       =  63,
	["Redfur Trading Post"]                 =  64,
	["Tomb of Anahbi"]                      =  65,
	["Burroot Kwama Mine"]                  =  66,
	["Gil-Var-Delle Abandoned Cave"]        =  67,
	["Nairume's Prison"]                    =  68,
	["The Orrery"]                          =  69,
	["Wormroot Depths"]                     =  70,
	
	-- Greenshade
	["Marbruk"]                             =  71,
	["Marbruk Outlaws Refuge"]              =  72,
	["Greenshade"]                          =  73,
	["Gurzag's Mine"]                       =  74,
	["Camp Gushnukbur"]                     =  75,
	["Shrouded Hollow"]                     =  76,
	["Fading Tree"]                         =  77,
	["Carac Dena"]                          =  78,
	["Silatar"]                             =  79,
	["Hollow Den"]                          =  80,
	["Shademist Enclave"]                   =  81,
	["Naril Nagaia"]                        =  82,
	["Woodhearth"]                          =  83,
	["Imperial Underground"]                =  84,
	["Ilmyris"]                             =  85,
	["Serpent's Grotto"]                    =  86,
	["The Underroot"]                       =  87,
	["Abecean Sea"]                         =  88,
	["Old Merchant Caves"]                  =  89,
	["Harridan's Lair"]                     =  90,
	["Nereid Temple Cave"]                  =  91,
	["Falinesti Cave"]                      =  92,
	["Hectahame Grotto"]                    =  93,
	["Valenheart"]                          =  94,
	["Isles of Torment"]                    =  95,
	["Barrow Trench"]                       =  96,
			
	-- Malbal Tor
	["Velyn Harbor"]                        =  97,
	["Malabal Tor Outlaws Refuge"]          =  98,
	["Malabal Tor"]                         =  99,
	["Stormwarden Undercroft"]              = 100,
	["Dead Man's Drop"]                     = 101,
	["Tomb of Apostates"]                   = 102,
	["Hoarvor Pit"]                         = 103,
	["Vulkwasten"]                          = 104,
	["Ogrim's Yawn"]                        = 105,
	["Abamath Ruins"]                       = 106,
	["Shrine of Mauloch"]                   = 107,
	["Shael Ruins"]                         = 108,
	["Belarate"]                            = 109,
	["Roots of Silvenar"]                   = 110,
	["Ouze"]                                = 111,
	["Baandari Trading Post"]               = 112,
	["Roots of Treehenge"]                  = 113,
	["Black Vine Ruins"]                    = 114,
	["The Hunting Grounds"]                 = 115,
	["Silvernar Throne Room"]               = 116,
		
	-- Reapers March
	["Reaper's March"]                      = 117,
	["Vinedusk Village Corridor"]           = 118,
	["Vinedusk Village"]                    = 119,
	["Khaj Rawlith"]                        = 120,
	["Senalana"]                            = 121,
	["Arenthia"]                            = 122,
	["Greenhill Catacombs"]                 = 123,
	["Thibaut's Cairn"]                     = 124,
	["Halls of Ichor"]                      = 125,
	["Rawl'kha"]                            = 126,
	["Rawl'kha Temple"]                     = 127,
	["Rawl'kha Outlaws Refuge"]             = 128,
	["Weeping Wind Cave"]                   = 129,
	["Moonmont Temple"]                     = 130,
	["Do'Krin Temple"]                      = 131,
	["The Five Finger Dance"]               = 132,
	["Claw's Strike"]                       = 133,
	["S'ren-ja Bandit Cave"]                = 134,
	["S'ren-ja Well"]                       = 135,
	["S'ren-ja Cave"]                       = 136,
	["Jode's Light"]                        = 137,
	["Kuna's Delve"]                        = 138,
	["Heart of the Wyrd Tree"]              = 139,
	["Fort Sphinxmoth"]                     = 140,
	["Fardir's Folly"]                      = 141,
	["Dune"]                                = 142,
	["Temple of the Dance"]                 = 143,
	["The Demi-Plane of Jode"]              = 144,
	["The Wild Hunt"]                       = 145,
	["Urcelmo's Betrayal"]                  = 146,
	["Den of Lorkhaj"]                      = 147,
	
	-- Daggerfall Covenant
	-- Stros M'Kai
	["Port Hunding"]                        = 148,
	["The Grave"]                           = 149,
	["Stros M'Kai"]                         = 150,
	["Goblin Mines"]                        = 151,
	["Bthzark"]                             = 152,
	
	-- Betnikh
	["Stonetooth Fortress"]                 = 153,
	["Betnikh"]                             = 154,
	["Bloodthorn Lair"]                     = 155,
	["Ancient Carzog's Demise"]             = 156,
	["Moriseli"]                            = 157,
	["Carzog's Demise"]                     = 158,
		
	-- Glenumbra
	["Daggerfall"]                          = 159,
	["Daggerfall Outlaws Refuge"]           = 160,
	["Glenumbra"]                           = 161,
	["Ilessan Tower"]                       = 162,
	["East Hut Portal Cave"]                = 163,
	["South Hut Portal Cave"]               = 164,
	["West Hut Portal Cave"]                = 165,
	["North Hut Portal Cave"]               = 166,
	["Silumm"]                              = 167,
	["Enduum"]                              = 168,
	["Dresan Keep"]                         = 169,
	["Aldcroft"]                            = 170,
	["The Mines of Khuras"]                 = 171,
	["Glenumbra Camlorn Keep"]              = 172,
	["Desolation's End"]                    = 173,
	["Ebon Crypt"]                          = 174,
	["Cath Bedraud"]                        = 175,
	["Angof's Sanctum"]                     = 176,
	["Tomb of Lost Kings"]                  = 177,
	["Cryptwatch Fort"]                     = 178,
	["Crosswych"]                           = 179,
	["Crosswych Mine"]                      = 180,
	
	-- Stormhaven
	["Koeglin Village"]                     = 181,
	["Koeglin Mine"]                        = 182,
	["Stormhaven"]                          = 183,
	["Alcaire Castle"]                      = 184,
	["Windridge Cave"]                      = 185,
	["Portdun Watch"]                       = 186,
	["Pariah Catacombs"]                    = 187,
	["Wayrest"]                             = 188,
	["Wayrest Outlaws Refuge"]              = 189,
	["Farangel's Delve"]                    = 190,
	["Bearclaw Mine"]                       = 191,
	["Godrun's Dream"]                      = 192,
	["Norvulk Ruins"]                       = 193,
	["Aphren's Tomb"]                       = 194,
	["Emeric's Dream"]                      = 195,
						
	-- Rivenspire
	["Rivenspire"]                          = 196,
	["Shornhelm"]                           = 197,
	["Shornhelm Outlaws Refuge"]            = 198,
	["Fevered Mews"]                        = 199,
	["Crestshade Mine"]                     = 200,
	["Doomcrag"]                            = 201,
	["Shadowfate Cavern"]                   = 202,
	["Hoarfrost Downs"]                     = 203,
	["Tribulation Crypt"]                   = 204,
	["Lorkrata Ruins"]                      = 205,
	["Edrald Undercroft"]                   = 206,
	["Flyleaf Catacombs"]                   = 207,
	["Northpoint"]                          = 208,
	["Breagha-Fin"]                         = 209,
	["Orc's Finger Ruins"]                  = 210,
	["Hildune's Secret Refuge"]             = 211,
	["Erokii Ruins"]                        = 212,
	["Shrouded Pass"]                       = 213,
				
	-- Alik'r Desert
	["Sentinel"]                            = 214,
	["Sentinel Outlaws Refuge"]             = 215,
	["Alik'r Desert"]                       = 216,
	["Shore Cave"]                          = 217,
	["Impervious Vault"]                    = 218,
	["Santaki"]                             = 219,
	["Salas En"]                            = 220,
	["The Portal Chamber"]                  = 221,
	["Ash'abah Pass"]                       = 222,
	["Yokudan Palace"]                      = 223,
	["Divad's Chagrin Mine"]                = 224,
	["Bergama"]                             = 225,
	["Magistrate's Basement"]               = 226,
	["Aldunz"]                              = 227,
	["The Master's Crypt"]                  = 228,
	["Kulati Mines"]                        = 229,
	["Coldrock Diggings"]                   = 230,
	["Sandblown Mine"]                      = 231,
	["Yldzuun"]                             = 232,
	["Kozanset"]                            = 233,
	["Smuggler King Tunnel"]                = 234,
	["Suturah's Crypt"]                     = 235,
		
	-- Bangkorai
	["Evermore"]                            = 236,
	["Evermore Outlaws Refuge"]             = 237,
	["Bangkorai"]                           = 238,
	["Bisnensel"]                           = 239,
	["Torog's Spite"]                       = 240,
	["Crypt of the Exiles"]                 = 241,
	["Troll's Toothpick"]                   = 242,
	["Nchu Duabthar Threshold"]             = 243,
	["Viridian Watch"]                      = 244,
	["Bangkorai Garrison"]                  = 245,
	["Sunken Road"]                         = 246,
	["Klathzgar"]                           = 247,
	["Rubble Butte"]                        = 248,
	["Nilata Ruins"]                        = 249,
	["Anexiel's Lair"]                      = 250,
	["Hallin's Stand"]                      = 251,
	["Onsi's Breath Mine"]                  = 252,
	["Hall of Heroes"]                      = 253,
	["The Far Shores"]                      = 254,
	
	-- Ebonheart Pact
	-- Bleakrock Isle
	["Bleakrock Village"]                   = 255,
	["Bleakrock Isle"]                      = 256,
	["Skyshroud Barrow"]                    = 257,
	["Hozzin's Folly"]                      = 258,
	["Orkey's Hollow"]                      = 259,
	["Last Rest"]                           = 260,
	
	-- Bal Foyen
	["Bal Foyen"]                           = 261,
	["Dhalmora"]                            = 262,
	["Smuggler Tunnel"]                     = 263,
	
	-- Stonefalls
	["Stonefalls"]                          = 264,
	["Davon's Watch"]                       = 265,
	["House Indoril Crypt"]                 = 266,
	["Davon's Watch Outlaws Refuge"]        = 267,
	["Charred Ridge"]                       = 268,
	["Ash Mountain"]                        = 269,
	["Inner Sea Armature"]                  = 270,
	["Emberflint Mine"]                     = 271,
	["Mephala's Nest"]                      = 272,
	["Fort Arand Dungeons"]                 = 273,
	["Ebonheart"]                           = 274,
	["Coral Heart Chamber"]                 = 275,
	["Softloam Cavern"]                     = 276,
	["Heimlyn Keep Reliquary"]              = 277,
	["Fort Virak Ruin"]                     = 278,
	["Iliath Temple Mines"]                 = 279,
	["Sheogorath's Tongue"]                 = 280,
	["Kragenmoor"]                          = 281,
	["House Dres Crypts"]                   = 282,
	["Hightide Hollow"]                     = 283,
	["Tormented Spire"]                     = 284,
		
	-- Deshaan
	["Deshaan"]                             = 285,
	["Quarantine Serk Catacombs"]           = 286,
	["Narsis"]                              = 287,
	["Narsis Ruins"]                        = 288,
	["Lady Llarel's Shelter"]               = 289,
	["Obsidian Gorge"]                      = 290,
	["Apothacarium"]                        = 291,
	["Mzithumz"]                            = 292,
	["Mournhold"]                           = 293,
	["Mournhold Sewers"]                    = 294,
	["Mournhold Outlaws Refuge"]            = 295,
	["The Triple Circle Mine"]              = 296,
	["Tribunal Temple"]                     = 297,
	["Bthanual"]                            = 298,
	["Lower Bthanual"]                      = 299,
	["Deepcrag Den"]                        = 300,
	["Shad Astula Underhalls"]              = 301,
	["Taleon's Crag"]                       = 302,
	["Vale of the Ghost Snake"]             = 303,
	["Tal'Deic Crypts"]                     = 304,
	["The Shrine of St. Veloth"]            = 305,
	["The Corpse Garden"]                   = 306,
	["Knife Ear Grotto"]                    = 307,
	["Eidolon's Hollow"]                    = 308,
	["Reservoir of Souls"]                  = 309,
	
	-- Shadowfen
	["Stormhold"]                           = 310,
	["Stormhold Guild Hall"]                = 311,
	["Stormhold Mortuary"]                  = 312,
	["Silyanorn Ruins"]                     = 313,
	["Shadowfen"]                           = 314,
	["Stormhold Outlaws Refuge"]            = 315,
	["Shrine of the Black Maw"]             = 316,
	["Odious Chapel"]                       = 317,
	["Mud Tree Mine"]                       = 318,
	["Mudshallow Cave"]                     = 319,
	["Ruins of Ten-Maur-Wolk"]              = 320,
	["Lair of the Skin Stealer"]            = 321,
	["Alten Corimont"]                      = 322,
	["Tsanji's Hideout"]                    = 323,
	["Atanaz Ruins"]                        = 324,
	["Broken Tusk"]                         = 325,
	["Onkobra Kwama Mine"]                  = 326,
	["Percolating Mire"]                    = 327,
	["Sunscale Ruins"]                      = 328,
	["Gandranen Ruins"]                     = 329,
	["Temple of Sul"]                       = 330,
	["Hissmir Ruins"]                       = 331,
	["White Rose Prison Dungeon"]           = 332,
	["Chid-Moska Ruins"]                    = 333,
	["Loriasel"]                            = 334,
	["Vision of the Hist"]                  = 335,
	
	-- Eastmarch
	["Windhelm"]                            = 336,
	["Windhelm Outlaws Refuge"]             = 337,
	["The Chill Hollow"]                    = 338,
	["Eastmarch"]                           = 339,
	["Cradlecrush Arena"]                   = 340,
	["Icehammer's Vault"]                   = 341,
	["Fort Morvunskar"]                     = 342,
	["Giant's Run"]                         = 343,
	["Fort Amol"]                           = 344,
	["Lost Knife Cave"]                     = 345,
	["The Frigid Grotto"]                   = 346,
	["Bonestrewn Crest"]                    = 347,
	["Wittestadr Crypts"]                   = 348,
	["Mistwatch Crevasse"]                  = 349,
	["Old Sord's Cave"]                     = 350,
	["Stormcrag Crypt"]                     = 351,
	["The Bastard's Tomb"]                  = 352,
	["Mzulft"]                              = 353,
	["Cragwallow"]                          = 354,
	
	-- The Rift
	["Shor's Stone"]                        = 355,
	["Shor's Stone Mine"]                   = 356,
	["The Rift"]                            = 357,
	["Fallowstone Vault"]                   = 358,
	["Northwind Mine"]                      = 359,
	["Vaults of Vernim"]                    = 360,
	["Snapleg Cave"]                        = 361,
	["Nimalten"]                            = 362,
	["Nimalten Barrow"]                     = 363,
	["Shroud Hearth Barrow"]                = 364,
	["Pinepeak Caverns"]                    = 365,
	["Taarengrav Barrow"]                   = 366,
	["Arcwind Point"]                       = 367,
	["Broken Helm Hollow"]                  = 368,
	["Avanchnzel"]                          = 369,
	["Riften"]                              = 370,
	["Riften Outlaws Refuge"]               = 371,
	["Fort Greenwall"]                      = 372,
	["Lost Prospect"]                       = 373,
	["Broken Helm"]                         = 374,
	["Forelhost"]                           = 375,
	["Trolhetta Cave"]                      = 376,
	["Trolhetta Summit"]                    = 377,
	
	-- Coldharbour
	["Stirk"]                               = 378,
	["Coldharbour"]                         = 379,
	["The Hollow City"]                     = 380,
	["Tower of Lies"]                       = 381,
	["Haj Uxith"]                           = 382,
	["Library of Dusk"]                     = 383,
	["Lightless Oubliette"]                 = 384,
	["Lightless Cell"]                      = 385,
	["Aba-Loria"]                           = 386,
	["Reaver Citadel Pyramid"]              = 387,
	["Holding Cells"]                       = 388,
	["The Cave of Trophies"]                = 389,
	["The Vault of Haman Forgefire"]        = 390,
	["Thane's Lair"]                        = 391,
	["The Black Forge"]                     = 392,
	["The Great Shackle"]                   = 393,
	["The Mooring"]                         = 394,
	["Grunda's Gatehouse"]                  = 395,
	["Mal Sorra's Tomb"]                    = 396,
	["The Manor of Revelry"]                = 397,
	["Cave of Revelry"]                     = 398,
	["The Wailing Maw"]                     = 399,
	["The Lost Fleet"]                      = 400,
	["Reaver Citadel Pyramid"]              = 401,
	["The Endless Stair"]                   = 402,
	
	-- Five Companions
	["The Wailing Prison"]                  = 403,
	["The Harborage"]                       = 404,
	["Vision of the Companions"]            = 405,
	["Foundry of Woe"]                      = 406,
	["The Worm's Retreat"]                  = 407,
	["Castle of Worms"]                     = 408,
	["Halls of Torment"]                    = 409,
	["Valley of Blades"]                    = 410,
	["Ancestral Crypt"]                     = 411,
	["Sancre Tor"]                          = 412,
	["Heart's Grief"]                       = 413,
	["Coldored Rooms"]                      = 414,
	
	-- Fighter's Guild
	["Buraniim"]                            = 415,
	["Dourstone Vault"]                     = 416,
	["Stonefang Cavern"]                    = 417,
	["Mzeneldt"]                            = 418,
	["Abagarlas"]                           = 419,
	["The Earth Forge"]                     = 420,
	["Ragnthar"]                            = 421,
	["Halls of Submission"]                 = 422,

	-- Mages Guild
	["Cheesemonger's Hollow"]               = 423,
	["Shivering Isles"]                     = 424,
	["Vuldngrav"]                           = 425,
	["Asakala"]                             = 426,
	["Circus of Cheerful Slaughter"]        = 427,
	["Chateau of the Ravenous Rodent"]      = 428,
	["Chateau Master Bedroom"]              = 429,
	["Eyevea"]                              = 430,
	
	-- Craglorn
	["Belkarth"]                            = 431,
	["Belkarth Outlaws Refuge"]             = 432,
	["Craglorn"]                            = 433,
	["Buried Sands"]                        = 434,
	["Tombs of the Na-Totambu"]             = 435,
	["Haddock's Market"]                    = 436,
	["Frost Monarch Lair"]                  = 437,
	["Storm Monarch Lair"]                  = 438,
	["Molavar"]                             = 439,
	["Balamath"]                            = 440,
	["Balamath Hall"]                       = 441,
	["Reinhold's Retreat"]                  = 442,
	["Dragonstar"]                          = 443,
	["Fearfangs Cavern"]                    = 444,
	["Sunken Lair"]                         = 445,
	["Serpent's Nest"]                      = 446,
	["Ilthag's Undertow"]                   = 447,
	["Exarch's Stronghold"]                 = 448,
	["The Howling Sepulchers"]              = 449,
	["Loth'Na Caverns"]                     = 450,
	["Skyreach Temple"]                     = 451,
	["Apex Stone Room"]                     = 452,
	["Rkundzelft"]                          = 453,
	["Hircine's Haunt"]                     = 454,
	["Elinhir Sewerworks"]                  = 455,
	["Mtharnaz"]                            = 456,
	["Ruins of Kardala"]                    = 457,
	["Chiselshriek Mine"]                   = 458,
	["Rkhardahrk"]                          = 459,
	["Zalgaz's Den"]                        = 460,
	
	-- Imperial City
	["Western Elsweyr Gate"]                = 461,
	["Eastern Elsweyr Gate"]                = 462,
	["Imperial Sewers Aldmeri Base"]        = 463,
	["Imperial City"]                       = 464,
	["Dragonfire Cathedral"]                = 465,
	["Northern High Rock Gate"]             = 466,
	["Southern High Rock Gate"]             = 467,
	["Cyrodiil"]                            = 468,
	["Imperial Sewers Daggerfall Base"]     = 469,
	["Southern Morrowind Gate"]             = 470,
	["Northern Morrowind Gate"]             = 471,
	["Imperial Sewers Ebonheart Base"]      = 472,
	
	-- Orsinium
	["Wrothgar"]                            = 473,
	["Nikolvara's Kennel"]                  = 474,
	["Orsinium "]                           = 475,
	["Orsinium Outlaws Refuge"]             = 476,
	["Frost Break Fort"]                    = 477,
	["Ice Heart's Lair"]                    = 478,
	["Scarp Keep"]                          = 479,
	["Orsinium Temple"]                     = 480,
	["Temple Rectory"]                      = 481,
	["Graystone Quarry Depths"]             = 482,
	["Honor's Rest Catacombs"]              = 483,
	["Halls of Honor"]                      = 484,
	["Bloody Knoll"]                        = 485,
	["Coldperch Cavern"]                    = 486,
	["Bonerock Cavern"]                     = 487,
	["Morkul"]                              = 488,
	["Morkul Descent "]                     = 489,
	["Morkuldin"]                           = 490,
	["Exile's Barrow"]                      = 491,
	["Zthenganaz"]                          = 492,
	["Fharun Prison"]                       = 493,
	["Fharun Stronghold"]                   = 494,
	["Sorrow"]                              = 495,
	["Argent Mine"]                         = 496,
	["Thukhozod's Sanctum"]                 = 497,
	["Watcher's Hold"]                      = 498,
	["Paragon's Remembrance"]               = 499,
	["Chambers of Loyalty"]                 = 500,
	["Temple Library"]                      = 501,
	["Path to the Moot"]                    = 502,
	
	-- Thieves Guild
	["Fulstrom Homestead"]                  = 503,
	["Fulstrom Catacombs"]                  = 504,
	["Abah's Landing"]                      = 505,
	["Safe House"]                          = 506,
	["Maw_of_Lorkaj_Base"]                  = 507,
	["Sulima Mansion"]                      = 508,
	["Hew's bane"]                          = 509,
	["Bahraha's Gloom"]                     = 510,
	["No Shira Citadel"]                    = 511,
	["Vermont Mansion"]                     = 512,
	["al-Danobia Tomb"]                     = 513,
	["Shark's Teeth Grotto"]                = 514,
	["Hubalajad Palace"]                    = 515,

	-- Dark Brotherhood
	["Anvil"]                               = 516,
	["Anvil Outlaws Refuge"]                = 517,
	["Gold Coast"]                          = 518,
	["Jarol's Estate"]                      = 519,
	["Jarol's Estate Wine Cellar"]          = 520,
	["Jarol's Estate Smuggling Tunnels"]    = 521,
	["Hrota Cave"]                          = 522,
	["Garlas Agea"]                         = 523,
	["Dark Brotherhood Sanctuary"]          = 524,
	["Kvatch"]                              = 525,
	["At-Himah Family Estate"]              = 526,
	["Jerall Mountains"]                    = 527,
	["Castle Anvil"]                        = 528,
	["Castle Kvatch"]                       = 529,
	["Enclave of the Hourglass"]            = 530,
	["Blackwood Borderlands"]               = 531,
	["Knightsgrave"]                        = 532,
	["Cathedral of Akatosh"]                = 533,
	
	-- Vvardenfell
	["Cold-Blood Cavern"]                   = 534,
	["Dyzera's Realm"]                      = 535,
	["Vvardenfell"]                         = 536,
	["Andrano Ancestral Tomb"]              = 537,
	["Vivec City"]                          = 538,
	["Vivec City Outlaws Refuge"]           = 539,
	["Palace Recieving Room"]               = 540,
	["Library of Vivec"]                    = 541,
	["Archcanon's Office"]                  = 542,
	["Hall of Justice"]                     = 543,
	["Sadrith Mora"]                        = 544,
	["Barilzar's Tower"]                    = 545,
	["Zaintiraris"]                         = 546,
	["Pinsun"]                              = 547,
	["Pulk"]                                = 548,
	["Zalkin-Sul Egg Mine"]                 = 549,
	["Mzanchend"]                           = 550,
	["Vassamsi Mine"]                       = 551,
	["Tusenend"]                            = 552,
	["Dreudurai Glass Mine"]                = 553,
	["Bal Ur"]                              = 554,
	["Zainsipilu"]                          = 555,
	["Balmora"]                             = 556,
	["Firemoth Island"]                     = 557,
	["Shulk Ore Mine"]                      = 558,
	["Vassir-Danat Mine"]                   = 559,
	["Ashurnibibi"]                         = 560,
	["Mallapi Cave"]                        = 561,
	["Kudanat Mine"]                        = 562,
	["Redoran Garrison"]                    = 563,
	["Ramimilk"]                            = 564,
	["Ashimanu Cave"]                       = 565,
	["Hleran Ancestral Tomb"]               = 566,
	["Gnisis Egg Mine"]                     = 567,
	["Ashalmawia"]                          = 568,
	["Prison of Xykenaz"]                   = 569,
	["Cavern of the Incarnate"]             = 570,
	["Skar"]                                = 571,
	["Galom Daeus"]                         = 572,
	["Nchuleft"]                            = 573,
	["Nchuleft Depths"]                     = 574,
	["Arkngthunch-Sturdumz"]                = 575,
	["Kaushtarari"]                         = 576,
	["Lord Vivec's Chambers"]               = 577,
	["Seht's Vault"]                        = 578,
	["Engineering Junction"]                = 579,
	["Dockworks"]                           = 580,
	["The Divinity Atelier"]                = 581,
	["Maintence Junction"]                  = 582,
	["Engineering Access"]                  = 583,
	["Atelier Courtyard"]                   = 584,
	["Clavicus Vile Shrine"]                = 585,
	["Dreloth Ancestral Tomb"]              = 586,
	["Veloth Ancestral Tomb"]               = 587,
	["Matus-Akin Egg Mine"]                 = 588,
	["Inanius Egg Mine"]                    = 589,
	["Khartag Point"]                       = 590,
	["Bal Fell"]                            = 591,
	
	-- Clockwork City
	["Dranil Kir Island"]                   = 592,
	["Clockwork City Vaults"]               = 593,
	["Clockwork City"]                      = 594,
	["Brass Fortress"]                      = 595,
	["Clockwork Basilica"]                  = 596,
	["Serviflume"]                          = 597,
	["Administration Nexus"]                = 598,
	["Mechanical Fundament"]                = 599,
	["Ventral Terminus"]                    = 600,
	["Incarnatorium"]                       = 601,
	["The Shadow Cleft"]                    = 602,
	["Mnemonic Planisphere"]                = 603,
	["Slag Town Outlaws Refuge"]            = 604,
	["Evergloom"]                           = 605,
	["Cogitum Centralis"]                   = 606,
	["Everwound Wellspring"]                = 607,
	["Halls of Regulation"]                 = 608,
	
   	-- SUMMERSET
	["Shimmerene"]                          = 609,
	["Summerset"]                           = 610,
	["Monastery Of Serene Harmony"]         = 611,
	["Shimmerene Waterworks"]               = 612,
	["Archon's Grove"]                      = 613,
	["Artaeum"]                             = 614,
	["The Dreaming Cave"]                   = 615,
	["Ceporah Tower"]                       = 616,
	["Red Temple Catacombs"]                = 617,
	["Rellenthil Sinkhole"]                 = 618,
	["Cey-Tarn Keep"]                       = 619,
	["The Vaults of Heinarwe"]              = 620,
	["Wastern Coraldale"]                   = 621,
	["Alinor"]                              = 622,
	["Alinor Royal Palace"]                 = 623,
	["Tor-Hame-Khard"]                      = 624,
	["Alinor Outlaws Refuge"]               = 625,
	["College of Psijics Ruins"]            = 626,
	["Psijic Relic Vaults"]                 = 627,
	["K'Tora's Mindscape"]                  = 628,
	["Eldbur Ruins"]                        = 629,
	["Cairnar's Mind Trap"]                 = 630,
	["Miriya's Mind Trap"]                  = 631,
	["Oriandra's Mind Trap"]                = 632,
	["Direnni Acropolis"]                   = 633,
	["Illumination Academy Stacks"]         = 634,
	["Sea Keep"]                            = 635,
	["Lillandril"]                          = 636,
	["College of Sapiarchs Labyrinth"]      = 637,
	["Saltbreeze Cave"]                     = 638,
	["King's Haven Pass"]                   = 639,
	["Eton Nir Grotto"]                     = 640,
	["The Spiral Skein"]                    = 641,
	["Ebon Sanctum"]                        = 642,
	["Traitor's Vault"]                     = 643,
	["Corgrad Wastes"]                      = 644,
	["Cathedral of Webs"]                   = 645,
	["Crystal Tower"]                       = 646,
	
	-- MURKMIRE
	["The Sunless Hollow"]                  = 647,
	["Norg-Tzel"]                           = 648,
	["Norg-Tzel Xanmeer"]                   = 649,
	["Lilmoth"]                             = 650,
	["Murkmire"]                            = 651,
	["Ixtaxh Xanmeer"]                      = 652,
	["Bright-Throat Village"]               = 653,
	["Blight Bog Sump"]                     = 654,
	["Wither-Vault"]                        = 655,
	["Dead-Water Village"]                  = 656,
	["Tsofeer Cavern"]                      = 657,
	["Tomb of Many Spears"]                 = 658,
	["Teeth of Sithis"]                     = 659,
	["Swallowed Grove"]                     = 660,
	["Singing Grotto"]                      = 661,
	["The Dreaming Nest"]                   = 662,
	["Xul-Thuxis"]                          = 663,
	["Root-Whisper Village"]                = 664,
	["Vakka-Box Xanmeer"]                   = 665,
	["Deep-Root"]                           = 666,
	["remnantofargon_base"]                 = 667,
	-- NORTHERN ELSWEYR
	["New-Moons Chamber"]                   = 668,
	["Dark-Moons Chamber"]                  = 668,
	["Full-Moons Chamnber"]                 = 670,
	["Halls of Colossus"]                   = 671,
	["Rimmen"]                              = 672,
	["Rimmen Palace Recusses"]              = 673,
	["Rimmen Palace Crypts"]                = 674,
	["Rimmen Palace"]                       = 675,
	["Rimmen Palace Courtyard"]             = 676,
	["Northern Elsweyr"]                    = 677,
	["Riverhold"]                           = 678,
	["Tomb of the Serpents"]                = 679,
	["Smuggler's Hideout"]                  = 680,
	["Abode of Ignominy"]                   = 681,
	["Predator Mesa"]                       = 682,
	["The Stitches"]                        = 683,
	["Sleepy Senche Mine"]                  = 684,
	["Cicatrice Caverns"]                   = 685,
	["Darkpool Mine"]                       = 686,
	["Merryvale Sugar Farm Caves"]          = 687,
	["Desert Wind Caverns"]                 = 688,
	["Hidden Moon Crypts"]                  = 689,
	["Arum-Khal's Realm"]                   = 690,
	["Hakoshae Tombs"]                      = 691,
	["Tenarr Zalviit Ossuary"]              = 692,
	["The Tangle"]                          = 693,
	["Skooma Cat's Cloister"]               = 694,
	["Meirvale Keep Dungeons"]              = 695,
	["Dov-Vahl Shrine"]                     = 696,
	["Sepulcher of Mischance"]              = 697,
	["Shadow Dance Temple"]                 = 698,
	["Vault of Heavenly Scourage"]          = 699,
	["Moon Gate of Anequina"]               = 700,
	["Jode's Core"]                         = 701,
	-- SOUTHERN ELSWEYR
	["Wind Scour Temple"]                   = 702,
	["Storm Talon Temple"]                  = 703,
	["Dark Water Temple"]                   = 704,
	["Vahlokzin's Domain"]                  = 705,
	["Vahlokzin's Lair"]                    = 706,
	["Senchal"]                             = 707,
	["Senchal Outlaws Refuge"]              = 708,
	["Senchal Palace"]                      = 709,
	["Southern Elsweyr"]                    = 710,
	["Tideholm"]                            = 711,
	["Dragonguard Sanctum"]                 = 712,
	["Moonlit Cove"]                        = 713,
	["Passage of Dad'na Ghaten"]            = 714,
	["Zazardi's Quarry and Mine"]           = 715,
	["Black Kiergo Arena"]                  = 716,
	["Forsaken Citadel"]                    = 717,
	["New Moon Fortress"]                   = 718,
	["Halls of the Highmane"]               = 719,
	["Path of Pride"]                       = 720,
	["Doomstone Keep"]                      = 721,
	["The Spilled Sand"]                    = 722,
	["Dragonhold"]                          = 723,
	["Jonelight Path"]                      = 724,
	-- WESTERN SKYRIM
	["Riften Ratway"]                       = 725,
	["Blackreach: Mzark Cavern"]            = 726,
	["Palace of Kings"]                     = 727,
	["Western Skyrim"]                      = 728,
	["Solitude"]                            = 729,
	["Kilkreath"]                           = 730,
	["Shadowgreen"]                         = 731,
	["Dragon Bridge Smuggler Caves"]        = 732,
	["Dragonhome"]                          = 733,
	["Mor Khazgur Mine"]                    = 734,
	["Chillwind Depths"]                    = 735,
	["Bleakridge Barrow"]                   = 736,
	["Red Eagle Ridge"]                     = 737,
	["Verglas Hollow"]                      = 738,
	["Frozen Coast"]                        = 739,
	["Morthal Barrow"]                      = 740,
	["Blackreach: Greymoor Caverns"]        = 741,
	["Kagnthamz"]                           = 742,
	["Tzinghalis"]                          = 743,
	["Lightless Hollow Mine"]               = 744,
	["Bthang Outpost"]                      = 745,
	["Blackreach: Dark Moon Grotto"]        = 746,
	["The Scraps"]                          = 747,
	["Might Barrow"]                        = 748,
	["The Undergrove"]                      = 749,
	["Greymoor Keep: West Wing"]            = 750,
	["Greymoor Keep"]                       = 751,
	["Gray Host Tunnels"]                   = 752,

	-- THE REACH
	["Gray Host Sanctuary"]                 = 753,
	["Grayhome"]                            = 754,
	["Castle Grayhome"]                     = 755,
	["Grayhome Ritual Chamber"]             = 756,
	["The Reach"]                           = 757,
	["Markarth"]                            = 758,
	["Understone Keep"]                     = 759,
	["Valthume"]                            = 760,
	["Reachwind Depths"]                    = 761,
	["Briar Rock Ruins"]                    = 762,
	["Briar Rock Crypts"]                   = 763,
	["Dead Crone Tower"]                    = 764,
	["Sanuarach Mine"]                      = 765,
	["Bthar-Zel"]                           = 766,
	["Bthar-Zel Bank"]                      = 767,
	["Bthar-Zel Vault"]                     = 768,
	["Lost Valley Redoubt"]                 = 769,
	["The Dark Descent"]                    = 770,
	["Gloomreach"]                          = 771,
	["Blackreach: Arkthzand"]               = 772,
	["Halls of Arkthzand"]                  = 773,
	["Nighthollow Keep"]                    = 774,
	["Chamber of the Dark Heart"]           = 775,
	["Nchuand-Zel"]                         = 776,
	["Arkthzand Orrery"]                    = 777,
	["Gray Haven"]                          = 778,
	
	-- Isle of Balfiera
	["Balfiera Ruins"]                      = 779,
	["Isle of Balfiera"]                    = 780,
	["Keywright's Gallery"]                 = 781,
	
		-- Blackwood
	["Imperial Cache Annex"]                = 782,
	["Ne Salas Cache Annex"]                = 783,
	["Imperial Sewers"]                     = 784,
	["Deadlands"]                           = 785,
	["Leyawiin"]                            = 786,
	["Blackwood"]                           = 787,
	["Undertow Cavern"]                     = 788,
	["Borderwatch Sewers"]                  = 789,
	["Borderwatch Courtyard"]               = 790,
	["Borderwatch Keep"]                    = 791,
	["Borderlands Crypt"]                   = 792,
	["Ayleid Ruins"]                        = 793,
	["Veyond"]                              = 794,
	["Doomvault Vulpinaz Upper level"]      = 795,
	["Doomvault Vulpinaz Mid Level"]        = 796,
	["Doomvault Vulpinaz Lower Level"]      = 797,
	["Anchor Chamber"]                      = 798,
	["Deepscorn Hollow"]                    = 799,
	["Gideon"]                              = 800,
	["Twyllbek Ruins"]                      = 801,
	["Tidewater Cave"]                      = 802,
	["Glenbridge Xanmeer"]                  = 803,
	["Doomvault Porcixid"]                  = 804,
	["Xal Irasotl"]                         = 805,
	["Bloodrun Cave"]                       = 806,
	["Welke"]                               = 807,
	["Leyawiin Castle"]                     = 808,
	["Xi-Tsei"]                             = 809,
	["Stonewastes Keep"]                    = 810,
	["Doomvault Capraxus"]                  = 811,
	["Vandacia's Deadline Keep"]            = 812,
	["Vunalk1"]                             = 813,
	["Deadlands: The Ashen Forest"]         = 814,
	["White Gold Tower Throne Room"]        = 815,
	["Xynaa's Sanctuary"]                   = 816,
	["Arpenia"]                             = 817,
	["Fort Redmane"]                        = 818,
	["Ruction Ring"]                        = 819,
	
	-- Deadlands
	["Lyranth's Hidden Lair"]               = 820,
	["Waking Flame Camp"]                   = 821,
	["Waking Flame Fargrave Conclave"]      = 822,
	["Fargrave City District"]              = 823,
	["The Bazaar"]                          = 824,
	["The Shambles"]                        = 825,
	["The Deadlands"]                       = 826,
	["False Martyrs' Folly"]                = 827,
	["The Bathhouse"]                       = 828,
	["The Collector's Villa"]               = 829,
	["Burning Gyre Keep"]                   = 830,
	["Brandfire Reformatory"]               = 831,
	["Reformatory Forge"]                   = 832,
	["Fleapits District"]                   = 833,
	["Fort Grief"]                          = 834,
	["Ardent Hope Outer Ward"]              = 835,
	["Deadlight"]                           = 836,
	["Deadlight Citadel"]                   = 837,
	["Deadlight Summit"]                    = 838,
	["Ardent Hope"]                         = 839,
	["Ardent Hope Citadel"]                 = 840,
	["The Path of Cinders"]                 = 841,
	["Xarxes Crucible"]                     = 842,
	["Isle of Joys"]                        = 843,
	["Hidden Chamber"]                      = 844,
	["Destruction's Solace"]                = 845,
	["Fort Sundercliff"]                    = 846,
}

-----------------------------------------
-- HELPER FUNCTIONS
-----------------------------------------

function Data:CollectMapIds()
	local sv = ZGV.sv.profile
	sv.mapids = {}

	for i = 0,1000 do
		local loczone, _ = _G.GetZoneInfo(i)
		sv.mapids[loczone] = i
	end
end
