-----------------------------------------
-- LOCALIZED GLOBAL VARIABLES
-----------------------------------------

local ZGV = _G.ZGV
local Data = {}
local Travel

-----------------------------------------
-- SAVED REFERENCES
-----------------------------------------

Travel = ZGV.Travel
Travel.Data = Data

-----------------------------------------
-- MAP DATA
-----------------------------------------

--[[
	\s*(\[.*\]) = ([0-9]*),\n  	->	\t\1 = \2,\n
	\t(\[.*\]) = ([0-9]*)		->	\t\2##\1 = \2
	\t[0-9]*##			->	\t
--]]


Data.MapIdsByName = {

	-- Aldmeri Dominion
	-- Khenarthi's Roost
	["Khenarthi's Roost"]                   =   1,
	["Temple of the Mourning Spring"]       =   2,
	["Hazak's Lair"]                        =   3,
	["Shattered Shoals"]                    =   4,
	["The Mangroves"]                       =   5,
	["Mistral"]                             =   6,
	["Cat's Eye Quay"]                      =   7,
	
	-- Auridon
	["Vulkhel Guard"]                       =   8,
	["Vulkhel Guard Outlaws Refuge"]        =   9,
	["Auridon"]                             =  10,
	["Del's Claim"]                         =  11,
	["Ondil"]                               =  12,
	["Phaer Catacombs"]                     =  13,
	["Inner Tanzelwil"]                     =  14,
	["Tower of the Vale - Temple"]          =  15,
	["Tower of the Vale - Rage"]            =  16,
	["Tower of the Vale - Bliss"]           =  17,
	["Tower of the Vale - Bliss Top"]       =  18,
	["Tower of the Vale - Despair"]         =  19,
	["Entila's Folly"]                      =  20,
	["Smugglerstunnel"]                     =  21,
	["Skywatch"]                            =  22,
	["The Veiled Keep"]                     =  23,
	["Ezduiin Undercroft"]                  =  24,
	["Wansalen"]                            =  25,
	["Quendeluun South Ruins"]              =  26,
	["Abandoned Mine"]                      =  27,
	["Bewan"]                               =  28,
	["Saltspray Cave"]                      =  29,
	["Torinaan Shrine"]                     =  30,
	["Mehrunes' Spite"]                     =  31,
	["The Vault of Exile"]                  =  32,
	["Firsthold"]                           =  33,
	["The Refuge of Dread"]                 =  34,
		
	-- Grahtwood
	["Haven"]                               =  35,
	["Haven Sewers"]                        =  36,
	["Grahtwood"]                           =  37,
	["Sacred Leap Grotto"]                  =  38,
	["The Scuttle Pit"]                     =  39,
	["Brackenleaf"]                         =  40,
	["Elden Root"]                          =  41,
	["Elden Root Mages Guild"]              =  42,
	["Elden Root Throne Room"]              =  43,
	["Elden Root Fighters Guild"]           =  44,
	["Elden Root Outlaws Refuge"]           =  45,
	["Cave of Broken Sails"]                =  46,
	["Gray Mire"]                           =  47,
	["Bone Orchard"]                        =  48,
	["Cathedral of the Golden Path"]        =  49,
	["Ne Salas"]                            =  50,
	["Mobar Mine"]                          =  51,
	["The Middens"]                         =  52,
	["Vinedeath Cave"]                      =  53,
	["Ossuary of Telacar"]                  =  54,
	["Laeloria Ruins"]                      =  55,
	["Karthdar"]                            =  56,
	["Cormount Prison"]                     =  57,
	["Reliquary Ruins"]                     =  58,
	["Reliquary Vault"]                     =  59,
	["Faltonia's Mine"]                     =  60,
	["Barkbite Cave"]                       =  61,
	["Barkbite Mine"]                       =  62,
	["Redfur Trading Post"]                 =  63,
	["Tomb of Anahbi"]                      =  64,
	["Burroot Kwama Mine"]                  =  65,
	["Gil-Var-Delle Abandoned Cave"]        =  66,
	["Nairume's Prison"]                    =  67,
	["The Orrery"]                          =  68,
	["Wormroot Depths"]                     =  69,
	
	-- Greenshade
	["Marbruk"]                             =  70,
	["Marbruk Outlaws Refuge"]              =  71,
	["Greenshade"]                          =  72,
	["Gurzag's Mine"]                       =  73,
	["Camp Gushnukbur"]                     =  74,
	["Shrouded Hollow"]                     =  75,
	["Fading Tree"]                         =  76,
	["Carac Dena"]                          =  77,
	["Silatar"]                             =  78,
	["Hollow Den"]                          =  79,
	["Shademist Enclave"]                   =  80,
	["Naril Nagaia"]                        =  81,
	["Woodhearth"]                          =  82,
	["Imperial Underground"]                =  83,
	["Ilmyris"]                             =  84,
	["Serpent's Grotto"]                    =  85,
	["The Underroot"]                       =  86,
	["Abecean Sea"]                         =  87,
	["Old Merchant Caves"]                  =  88,
	["Harridan's Lair"]                     =  89,
	["Nereid Temple Cave"]                  =  90,
	["Falinesti Cave"]                      =  91,
	["Hectahame Grotto"]                    =  92,
	["Valenheart"]                          =  93,
	["Isles of Torment"]                    =  94,
	["Barrow Trench"]                       =  95,
			
	-- Malbal Tor
	["Velyn Harbor"]                        =  96,
	["Malabal Tor Outlaws Refuge"]          =  97,
	["Malabal Tor"]                         =  98,
	["Stormwarden Undercroft"]              =  99,
	["Dead Man's Drop"]                     = 100,
	["Tomb of Apostates"]                   = 101,
	["Hoarvor Pit"]                         = 102,
	["Vulkwasten"]                          = 103,
	["Ogrim's Yawn"]                        = 104,
	["Abamath Ruins"]                       = 105,
	["Shrine of Mauloch"]                   = 106,
	["Shael Ruins"]                         = 107,
	["Belarate"]                            = 108,
	["Roots of Silvenar"]                   = 109,
	["Ouze"]                                = 110,
	["Baandari Trading Post"]               = 111,
	["Roots of Treehenge"]                  = 112,
	["Black Vine Ruins"]                    = 113,
	["The Hunting Grounds"]                 = 114,
	["Silvernar Throne Room"]               = 115,
			
	-- Reapers March
	["Reaper's March"]                      = 116,
	["Vinedusk Village Corridor"]           = 117,
	["Vinedusk Village"]                    = 118,
	["Khaj Rawlith"]                        = 119,
	["Senalana"]                            = 120,
	["Arenthia"]                            = 121,
	["Greenhill Catacombs"]                 = 122,
	["Thibaut's Cairn"]                     = 123,
	["Halls of Ichor"]                      = 124,
	["Rawl'kha"]                            = 125,
	["Rawl'kha Temple"]                     = 126,
	["Rawl'kha Outlaws Refuge"]             = 127,
	["Weeping Wind Cave"]                   = 128,
	["Moonmont Temple"]                     = 129,
	["Do'Krin Temple"]                      = 130,
	["The Five Finger Dance"]               = 131,
	["Claw's Strike"]                       = 132,
	["S'ren-ja Bandit Cave"]                = 133,
	["S'ren-ja Well"]                       = 134,
	["S'ren-ja Cave"]                       = 135,
	["Jode's Light"]                        = 136,
	["Kuna's Delve"]                        = 137,
	["Heart of the Wyrd Tree"]              = 138,
	["Fort Sphinxmoth"]                     = 139,
	["Fardir's Folly"]                      = 140,
	["Dune"]                                = 141,
	["Temple of the Dance"]                 = 142,
	["The Demi-Plane of Jode"]              = 143,
	["The Wild Hunt"]                       = 144,
	["Urcelmo's Betrayal"]                  = 145,
	["Den of Lorkhaj"]                      = 146,
	
	-- Daggerfall Covenant
	-- Stros M'Kai
	["Port Hunding"]                        = 147,
	["The Grave"]                           = 148,
	["Stros M'Kai"]                         = 149,
	["Goblin Mines"]                        = 150,
	["Bthzark"]                             = 151,
		
	-- Betnikh
	["Stonetooth Fortress"]                 = 152,
	["Betnikh"]                             = 153,
	["Bloodthorn Lair"]                     = 154,
	["Ancient Carzog's Demise"]             = 155,
	["Moriseli"]                            = 156,
	["Carzog's Demise"]                     = 157,
		
	-- Glenumbra
	["Daggerfall"]                          = 158,
	["Daggerfall Outlaws Refuge"]           = 159,
	["Glenumbra"]                           = 160,
	["Ilessan Tower"]                       = 161,
	["East Hut Portal Cave"]                = 162,
	["South Hut Portal Cave"]               = 163,
	["West Hut Portal Cave"]                = 164,
	["North Hut Portal Cave"]               = 165,
	["Silumm"]                              = 166,
	["Enduum"]                              = 167,
	["Dresan Keep"]                         = 168,
	["Aldcroft"]                            = 169,
	["The Mines of Khuras"]                 = 170,
	["Glenumbra Camlorn Keep"]              = 171,
	["Desolation's End"]                    = 172,
	["Ebon Crypt"]                          = 173,
	["Cath Bedraud"]                        = 174,
	["Angof's Sanctum"]                     = 175,
	["Tomb of Lost Kings"]                  = 176,
	["Cryptwatch Fort"]                     = 177,
	["Crosswych"]                           = 178,
	["Crosswych Mine"]                      = 179,
	
	-- Stormhaven
	["Koeglin Village"]                     = 180,
	["Stormhaven"]                          = 181,
	["Alcaire Castle"]                      = 182,
	["Windridge Cave"]                      = 183,
	["Portdun Watch"]                       = 184,
	["Pariah Catacombs"]                    = 185,
	["Wayrest"]                             = 186,
	["Wayrest Outlaws Refuge"]              = 187,
	["Farangel's Delve"]                    = 188,
	["Bearclaw Mine"]                       = 189,
	["Godrun's Dream"]                      = 190,
	["Norvulk Ruins"]                       = 191,
	["Aphren's Tomb"]                       = 192,
	["Emeric's Dream"]                      = 193,
						
	-- Rivenspire
	["Rivenspire"]                          = 194,
	["Shornhelm"]                           = 195,
	["Shornhelm Outlaws Refuge"]            = 196,
	["Fevered Mews"]                        = 197,
	["Crestshade Mine"]                     = 198,
	["Doomcrag"]                            = 199,
	["Shadowfate Cavern"]                   = 200,
	["Hoarfrost Downs"]                     = 201,
	["Tribulation Crypt"]                   = 202,
	["Lorkrata Ruins"]                      = 203,
	["Edrald Undercroft"]                   = 204,
	["Flyleaf Catacombs"]                   = 205,
	["Northpoint"]                          = 206,
	["Breagha-Fin"]                         = 207,
	["Orc's Finger Ruins"]                  = 208,
	["Hildune's Secret Refuge"]             = 209,
	["Erokii Ruins"]                        = 210,
	["Shrouded Pass"]                       = 211,
				
	-- Alik'r Desert
	["Sentinel"]                            = 212,
	["Sentinel Outlaws Refuge"]             = 213,
	["Alik'r Desert"]                       = 214,
	["Shore Cave"]                          = 215,
	["Impervious Vault"]                    = 216,
	["Santaki"]                             = 217,
	["Salas En"]                            = 218,
	["The Portal Chamber"]                  = 219,
	["Ash'abah Pass"]                       = 220,
	["Yokudan Palace"]                      = 221,
	["Divad's Chagrin Mine"]                = 222,
	["Bergama"]                             = 223,
	["Magistrate's Basement"]               = 224,
	["Aldunz"]                              = 225,
	["The Master's Crypt"]                  = 226,
	["Kulati Mines"]                        = 227,
	["Coldrock Diggings"]                   = 228,
	["Sandblown Mine"]                      = 229,
	["Yldzuun"]                             = 230,
	["Kozanset"]                            = 231,
	["Smuggler King Tunnel"]                = 232,
	["Suturah's Crypt"]                     = 233,
		
	-- Bangkorai
	["Evermore"]                            = 234,
	["Evermore Outlaws Refuge"]             = 235,
	["Bangkorai"]                           = 236,
	["Bisnensel"]                           = 237,
	["Torog's Spite"]                       = 238,
	["Crypt of the Exiles"]                 = 239,
	["Troll's Toothpick"]                   = 240,
	["Nchu Duabthar Threshold"]             = 241,
	["Viridian Watch"]                      = 242,
	["Bangkorai Garrison"]                  = 243,
	["Sunken Road"]                         = 244,
	["Klathzgar"]                           = 245,
	["Rubble Butte"]                        = 246,
	["Nilata Ruins"]                        = 247,
	["Anexiel's Lair"]                      = 248,
	["Hallin's Stand"]                      = 249,
	["Onsi's Breath Mine"]                  = 250,
	["Hall of Heroes"]                      = 251,
	["The Far Shores"]                      = 252,
	
	-- Ebonheart Pact
	-- Bleakrock Isle
	["Bleakrock Village"]                   = 253,
	["Bleakrock Isle"]                      = 254,
	["Skyshroud Barrow"]                    = 255,
	["Hozzin's Folly"]                      = 256,
	["Orkey's Hollow"]                      = 257,
	["Last Rest"]                           = 258,
	
	-- Bal Foyen
	["Bal Foyen"]                           = 259,
	["Dhalmora"]                            = 260,
	["Smuggler Tunnel"]                     = 261,
	
	-- Stonefalls
	["Stonefalls"]                          = 262,
	["Davon's Watch"]                       = 263,
	["House Indoril Crypt"]                 = 264,
	["Davon's Watch Outlaws Refuge"]        = 265,
	["Charred Ridge"]                       = 266,
	["Ash Mountain"]                        = 267,
	["Inner Sea Armature"]                  = 268,
	["Emberflint Mine"]                     = 269,
	["Mephala's Nest"]                      = 270,
	["Fort Arand Dungeons"]                 = 271,
	["Ebonheart"]                           = 272,
	["Coral Heart Chamber"]                 = 273,
	["Softloam Cavern"]                     = 274,
	["Heimlyn Keep Reliquary"]              = 275,
	["Fort Virak Ruin"]                     = 276,
	["Iliath Temple Mines"]                 = 277,
	["Sheogorath's Tongue"]                 = 278,
	["Kragenmoor"]                          = 279,
	["House Dres Crypts"]                   = 280,
	["Hightide Hollow"]                     = 281,
	["Tormented Spire"]                     = 282,
		
	
	-- Deshaan
	["Deshaan"]                             = 283,
	["Quarantine Serk Catacombs"]           = 284,
	["Narsis"]                              = 285,
	["Narsis Ruins"]                        = 286,
	["Lady Llarel's Shelter"]               = 287,
	["Obsidian Gorge"]                      = 288,
	["Apothacarium"]                        = 289,
	["Mzithumz"]                            = 290,
	["Mournhold"]                           = 291,
	["Mournhold Sewers"]                    = 292,
	["Mournhold Outlaws Refuge"]            = 293,
	["The Triple Circle Mine"]              = 294,
	["Tribunal Temple"]                     = 295,
	["Bthanual"]                            = 296,
	["Lower Bthanual"]                      = 297,
	["Deepcrag Den"]                        = 298,
	["Shad Astula Underhalls"]              = 299,
	["Taleon's Crag"]                       = 300,
	["Vale of the Ghost Snake"]             = 301,
	["Tal'Deic Crypts"]                     = 302,
	["The Shrine of St. Veloth"]            = 303,
	["The Corpse Garden"]                   = 304,
	["Knife Ear Grotto"]                    = 305,
	["Eidolon's Hollow"]                    = 306,
	["Reservoir of Souls"]                  = 307,
	
	-- Shadowfen
	["Stormhold"]                           = 308,
	["Stormhold Guild Hall"]                = 309,
	["Stormhold Mortuary"]                  = 310,
	["Silyanorn Ruins"]                     = 311,
	["Shadowfen"]                           = 312,
	["Stormhold Outlaws Refuge"]            = 313,
	["Shrine of the Black Maw"]             = 314,
	["Odious Chapel"]                       = 315,
	["Mud Tree Mine"]                       = 316,
	["Mudshallow Cave"]                     = 317,
	["Ruins of Ten-Maur-Wolk"]              = 318,
	["Lair of the Skin Stealer"]            = 319,
	["Alten Corimont"]                      = 320,
	["Tsanji's Hideout"]                    = 321,
	["Atanaz Ruins"]                        = 322,
	["Broken Tusk"]                         = 323,
	["Onkobra Kwama Mine"]                  = 324,
	["Percolating Mire"]                    = 325,
	["Sunscale Ruins"]                      = 326,
	["Gandranen Ruins"]                     = 327,
	["Temple of Sul"]                       = 328,
	["Hissmir Ruins"]                       = 329,
	["White Rose Prison Dungeon"]           = 330,
	["Chid-Moska Ruins"]                    = 331,
	["Loriasel"]                            = 332,
	["Vision of the Hist"]                  = 333,
	
	-- Eastmarch
	["Windhelm"]                            = 334,
	["Windhelm Outlaws Refuge"]             = 335,
	["The Chill Hollow"]                    = 336,
	["Eastmarch"]                           = 337,
	["Cradlecrush Arena"]                   = 338,
	["Icehammer's Vault"]                   = 339,
	["Fort Morvunskar"]                     = 340,
	["Giant's Run"]                         = 341,
	["Fort Amol"]                           = 342,
	["Lost Knife Cave"]                     = 343,
	["The Frigid Grotto"]                   = 344,
	["Bonestrewn Crest"]                    = 345,
	["Wittestadr Crypts"]                   = 346,
	["Mistwatch Crevasse"]                  = 347,
	["Old Sord's Cave"]                     = 348,
	["Stormcrag Crypt"]                     = 349,
	["The Bastard's Tomb"]                  = 350,
	["Mzulft"]                              = 351,
	["Cragwallow"]                          = 352,
	
	-- The Rift
	["Shor's Stone"]                        = 353,
	["Shor's Stone Mine"]                   = 354,
	["The Rift"]                            = 355,
	["Fallowstone Vault"]                   = 356,
	["Northwind Mine"]                      = 357,
	["Vaults of Vernim"]                    = 358,
	["Snapleg Cave"]                        = 359,
	["Nimalten"]                            = 360,
	["Nimalten Barrow"]                     = 361,
	["Shroud Hearth Barrow"]                = 362,
	["Pinepeak Caverns"]                    = 363,
	["Taarengrav Barrow"]                   = 364,
	["Arcwind Point"]                       = 365,
	["Broken Helm Hollow"]                  = 366,
	["Avanchnzel"]                          = 367,
	["Riften"]                              = 368,
	["Riften Outlaws Refuge"]               = 369,
	["Fort Greenwall"]                      = 370,
	["Lost Prospect"]                       = 371,
	["Broken Helm"]                         = 372,
	["Forelhost"]                           = 373,
	["Trolhetta Cave"]                      = 374,
	["Trolhetta Summit"]                    = 375,
	
	-- Coldharbour
	["Stirk"]                               = 376,
	["Coldharbour"]                         = 377,
	["The Hollow City"]                     = 378,
	["Tower of Lies"]                       = 379,
	["Haj Uxith"]                           = 380,
	["Library of Dusk"]                     = 381,
	["Lightless Oubliette"]                 = 382,
	["Lightless Cell"]                      = 383,
	["Aba-Loria"]                           = 384,
	["Reaver Citadel Pyramid"]              = 385,
	["Holding Cells"]                       = 386,
	["The Cave of Trophies"]                = 387,
	["The Vault of Haman Forgefire"]        = 388,
	["Thane's Lair"]                        = 389,
	["The Black Forge"]                     = 390,
	["The Great Shackle"]                   = 391,
	["The Mooring"]                         = 392,
	["Grunda's Gatehouse"]                  = 393,
	["Mal Sorra's Tomb"]                    = 394,
	["The Manor of Revelry"]                = 395,
	["Cave of Revelry"]                     = 396,
	["The Wailing Maw"]                     = 397,
	["The Lost Fleet"]                      = 398,
	["Reaver Citadel Pyramid"]              = 399,
	["The Endless Stair"]                   = 400,
	
	-- Five Companions
	["The Wailing Prison"]                  = 401,
	["The Harborage"]                       = 402,
	["Vision of the Companions"]            = 403,
	["Foundry of Woe"]                      = 404,
	["The Worm's Retreat"]                  = 405,
	["Castle of Worms"]                     = 406,
	["Halls of Torment"]                    = 407,
	["Valley of Blades"]                    = 408,
	["Ancestral Crypt"]                     = 409,
	["Sancre Tor"]                          = 410,
	["Heart's Grief"]                       = 411,
	["Coldored Rooms"]                      = 412,
	
	-- Fighter's Guild
	["Buraniim"]                            = 413,
	["Dourstone Vault"]                     = 414,
	["Stonefang Cavern"]                    = 415,
	["Mzeneldt"]                            = 416,
	["Abagarlas"]                           = 417,
	["The Earth Forge"]                     = 418,
	["Ragnthar"]                            = 419,
	["Halls of Submission"]                 = 420,

	-- Mages Guild
	["Cheesemonger's Hollow"]               = 421,
	["Shivering Isles"]                     = 422,
	["Vuldngrav"]                           = 423,
	["Asakala"]                             = 424,
	["Circus of Cheerful Slaughter"]        = 425,
	["Chateau of the Ravenous Rodent"]      = 426,
	["Chateau Master Bedroom"]              = 427,
	["Eyevea"]                              = 428,
	
	-- Craglorn
	["Belkarth"]                            = 429,
	["Belkarth Outlaws Refuge"]             = 430,
	["Craglorn"]                            = 431,
	["Buried Sands"]                        = 432,
	["Tombs of the Na-Totambu"]             = 433,
	["Haddock's Market"]                    = 434,
	["Frost Monarch Lair"]                  = 435,
	["Storm Monarch Lair"]                  = 436,
	["Molavar"]                             = 437,
	["Balamath"]                            = 438,
	["Balamath Hall"]                       = 439,
	["Reinhold's Retreat"]                  = 440,
	["Dragonstar"]                          = 441,
	["Fearfangs Cavern"]                    = 442,
	["Sunken Lair"]                         = 443,
	["Serpent's Nest"]                      = 444,
	["Ilthag's Undertow"]                   = 445,
	["Exarch's Stronghold"]                 = 446,
	["The Howling Sepulchers"]              = 447,
	["Loth'Na Caverns"]                     = 448,
	["Skyreach Temple"]                     = 449,
	["Apex Stone Room"]                     = 450,
	["Rkundzelft"]                          = 451,
	["Hircine's Haunt"]                     = 452,
	["Elinhir Sewerworks"]                  = 453,
	["Mtharnaz"]                            = 454,
	["Ruins of Kardala"]                    = 455,
	["Chiselshriek Mine"]                   = 456,
	["Rkhardahrk"]                          = 457,
	["Zalgaz's Den"]                        = 458,
	
	-- Imperial City
	["Western Elsweyr Gate"]                = 444,
	["Eastern Elsweyr Gate"]                = 445,
	["Imperial Sewers Aldmeri Base"]        = 446,
	["Imperial City"]                       = 447,
	["Dragonfire Cathedral"]                = 448,
	["Northern High Rock Gate"]             = 449,
	["Southern High Rock Gate"]             = 450,
	["Cyrodiil"]                            = 451,
	["Imperial Sewers Daggerfall Base"]     = 452,
	["Southern Morrowind Gate"]             = 453,
	["Northern Morrowind Gate"]             = 454,
	["Imperial Sewers Ebonheart Base"]      = 455,
	
	-- Orsinium
	["Wrothgar"]                            = 456,
	["Nikolvara's Kennel"]                  = 457,
	["Orsinium "]                           = 458,
	["Orsinium Outlaws Refuge"]             = 459,
	["Frost Break Fort"]                    = 460,
	["Ice Heart's Lair"]                    = 461,
	["Scarp Keep"]                          = 462,
	["Orsinium Temple"]                     = 463,
	["Temple Rectory"]                      = 464,
	["Graystone Quarry Depths"]             = 465,
	["Honor's Rest Catacombs"]              = 466,
	["Halls of Honor"]                      = 467,
	["Bloody Knoll"]                        = 468,
	["Coldperch Cavern"]                    = 469,
	["Bonerock Cavern"]                     = 470,
	["Morkul"]                              = 471,
	["Morkul Descent "]                     = 472,
	["Morkuldin"]                           = 473,
	["Exile's Barrow"]                      = 474,
	["Zthenganaz"]                          = 475,
	["Fharun Prison"]                       = 476,
	["Fharun Stronghold"]                   = 477,
	["Sorrow"]                              = 478,
	["Argent Mine"]                         = 479,
	["Thukhozod's Sanctum"]                 = 480,
	["Watcher's Hold"]                      = 481,
	["Paragon's Remembrance"]               = 482,
	["Chambers of Loyalty"]                 = 483,
	["Temple Library"]                      = 484,
	["Temple Undertunnels"]                 = 485,
	
	-- Thieves Guild
	["Fulstrom Homestead"]                  = 486,
	["Fulstrom Catacombs"]                  = 487,
	["Abah's Landing"]                      = 488,
	["Safe House"]                          = 489,
	["Maw_of_Lorkaj_Base"]                  = 490,
	["Sulima Mansion"]                      = 491,
	["Hew's bane"]                          = 492,
	["Bahraha's Gloom"]                     = 493,
	["No Shira Citadel"]                    = 494,
	["Vermont Mansion"]                     = 495,
	["al-Danobia Tomb"]                     = 496,
	["Shark's Teeth Grotto"]                = 497,
	["Hubalajad Palace"]                    = 498,

	-- Dark Brotherhood
	["Anvil"]                               = 499,
	["Anvil Outlaws Refuge"]                = 500,
	["Gold Coast"]                          = 501,
	["Jarol's Estate"]                      = 502,
	["Jarol's Estate Wine Cellar"]          = 503,
	["Jarol's Estate Smuggling Tunnels"]    = 504,
	["Hrota Cave"]                          = 505,
	["Garlas Agea"]                         = 506,
	["Dark Brotherhood Sanctuary"]          = 507,
	["Kvatch"]                              = 508,
	["At-Himah Family Estate"]              = 509,
	["Jerall Mountains"]                    = 510,
	["Castle Anvil"]                        = 511,
	["Castle Kvatch"]                       = 512,
	["Enclave of the Hourglass"]            = 513,
	["Blackwood Borderlands"]               = 514,
	["Knightsgrave"]                        = 515,
	["Cathedral of Akatosh"]                = 516,
	
	-- Vvardenfell
	["Vvardenfell"]                         = 517,
	["Andrano Ancestral Tomb"]              = 518,
	["Vivec City"]                          = 519,
	["Vivec City Outlaws Refuge"]           = 520,
	["Palace Recieving Room"]               = 521,
	["Library of Vivec"]                    = 522,
	["Archcanon's Office"]                  = 523,
	["Hall of Justice"]                     = 524,
	["Sadrith Mora"]                        = 525,
	["Barilzar's Tower"]                    = 526,
	["Zaintiraris"]                         = 527,
	["Pinsun"]                              = 528,
	["Pulk"]                                = 529,
	["Zalkin-Sul Egg Mine"]                 = 530,
	["Mzanchend"]                           = 531,
	["Vassamsi Mine"]                       = 532,
	["Tusenend"]                            = 533,
	["Dreudurai Glass Mine"]                = 534,
	["Bal Ur"]                              = 535,
	["Zainsipilu"]                          = 536,
	["Balmora"]                             = 537,
	["Firemoth Island"]                     = 538,
	["Shulk Ore Mine"]                      = 539,
	["Vassir-Danat Mine"]                   = 540,
	["Ashurnibibi"]                         = 541,
	["Mallapi Cave"]                        = 542,
	["Kudanat Mine"]                        = 543,
	["Redoran Garrison"]                    = 544,
	["Ramimilk"]                            = 545,
	["Ashimanu Cave"]                       = 546,
	["Hleran Ancestral Tomb"]               = 547,
	["Gnisis Egg Mine"]                     = 548,
	["Ashalmawia"]                          = 549,
	["Prison of Xykenaz"]                   = 550,
	["Cavern of the Incarnate"]             = 551,
	["Skar"]                                = 552,
	["Galom Daeus"]                         = 553,
	["Nchuleft"]                            = 554,
	["Nchuleft Depths"]                     = 555,
	["Arkngthunch-Sturdumz"]                = 556,
	["Kaushtarari"]                         = 557,
	["Lord Vivec's Chambers"]               = 558,
	["Seht's Vault"]                        = 559,
	["Maintence Junction"]                  = 560,
	["Engineering Junction"]                = 561,
	["The Divinity Atelier"]                = 562,
	["Dockworks"]                           = 563,
	["Engineering Access"]                  = 564,
	["Atelier Courtyard"]                   = 565,
	["Dreloth Ancestral Tomb"]              = 566,
	["Veloth Ancestral Tomb"]               = 567,
	["Matus-Akin Egg Mine"]                 = 568,
	["Inanius Egg Mine"]                    = 569,
	["Khartag Point"]                       = 570,
	["Bal Fell"]                            = 571,
	
	-- Clockwork City
	["Clockwork City Vaults"]               = 572,
	["Clockwork City"]                      = 573,
	["Brass Fortress"]                      = 574,
	["Clockwork Basilica"]                  = 575,
	["Serviflume"]                          = 576,
	["Administration Nexus"]                = 577,
	["Mechanical Fundament"]                = 578,
	["Ventral Terminus"]                    = 579,
	["Incarnatorium"]                       = 580,
	["The Shadow Cleft"]                    = 581,
	["Mnemonic Planisphere"]                = 582,
	["Slag Town Outlaws Refuge"]            = 583,
	["Evergloom"]                           = 584,
	["Cogitum Centralis"]                   = 585,
	["Everwound Wellspring"]                = 586,
	["Halls of Regulation"]                 = 587,
	
   	-- SUMMERSET
	["Summerset"]                           = 588,
	["Alinor"]                              = 589,
	["Lillandril"]                          = 590,
	["Shimmerene"]                          = 591,
	["Sunhold"]                             = 592,
	["Monastery Of Serene Harmony"]         = 593,
	["Shimmerene Waterworks"]               = 594,
	["Tor-Hame-Khard"]                      = 595,
	["Archon's Grove"]                      = 596,
	["Artaeum"]                             = 597,
	["The Dreaming Cave"]                   = 598,
	["Ceporah Tower"]                       = 599,
	["Red Temple Catacombs"]                = 600,
	["Rellenthil Sinkhole"]                 = 601,
	["Cey-Tarn Keep"]                       = 602,
	["The Gorge - Cey-Tarn Keep"]           = 603,
	["The Vaults of Heinarwe"]              = 604,
	["Altar Room"]                          = 605,
	["Wasten Coraldale"]                    = 606,
	["Alinor Royal Palace"]                 = 607,
	["Eldbur Ruins"]                        = 608,
	["Cairnar's Mind Trap"]                 = 609,
	["Miriya's Mind Trap"]                  = 610,
	["Oriandra's Mind Trap"]                = 611,
	["College of Psijics Ruins"]            = 612,
	["Psijic Relic Vaults"]                 = 613,
	["K'Tora's Mindscape"]                  = 614,
	["Direnni Acropolis"]                   = 615,
	["King's Haven Pass"]                   = 616,
	["Coral-Splitter Caves"]                = 617,
	["Ebon Sanctum"]                        = 618,
	["Illumination Academy Stacks"]         = 619,
	["Sea Keep"]                            = 620,
	["College of Sapiarchs Labyrinth"]      = 621,
	["Saltbreeze Cave"]                     = 622,
	["Eton Nir Grotto"]                     = 623,
	["The Spiral Skein"]                    = 624,
	["Traitor's Vault"]                     = 625,
	["Evergloam"]                           = 626,
	["Corgrad Wastes"]                      = 627,
	["Karnwasten"]                          = 628,
	["Cathedral of Webs"]                   = 629,
	["Crystal Tower"]                       = 630,
	["Cloudrest"]                           = 631,
	["Rellenthil"]                          = 632,
	
	-- MURKMIRE
	["Lilmoth"]                             = 634,
	["Murkmire"]                            = 635,
	["Ixtaxh Xanmeer"]                      = 636,
	["Bright-Throat Village"]               = 637,
	["Blight Bog Sump"]                     = 638,
	["Wither-Vault"]                        = 639,
	["Swallowed Grove"]                     = 640,
	["Dead-Water Village"]                  = 641,
	["Tomb of Many Spears"]                 = 642,
	["The Dreaming Nest"]                   = 643,
	["The Mists"]                           = 644,
	["Xul-Thuxis"]                          = 645,
	["Root-Whisper Village"]                = 646,
	["Vakka-Bok Village"]                   = 647,
	["Deep-Root"]                           = 648,
	["Remnant of Argon"]                    = 649,

	-- NORTHERN ELSWEYR
	["Elsweyr"]                             = 650,
	["Rimmen"]                              = 651,
	["Riverhold"]                           = 652,
	["Adobe of Ignominy"]                   = 653,
	["Tomb of the Serpents"]                = 654,
	["Smuggler's Hideout"]                  = 655,
	["The Stitches"]                        = 656,
	["Sleepy Senche Mine"]                  = 657,
	["Cicatrice Caverns"]                   = 658,
	["Meirvale Keep Dungeons"]              = 659,
	["Meirvale Keep Courtyard"]             = 660,
	["Meirvale Keep Palace"]                = 661,
	["Meirvale Keep Dugout"]                = 662,
	["Rimmen Palace Recesses"]              = 663,
	["Desert Wind Caverns"]                 = 664,
	["Riverhold"]                           = 665,
	["Hakoshae Tombs"]                      = 666,
	["Merryvale Sugar Farm Caves"]          = 667,
	["Skooma Cat's Cloister"]               = 668,
	["Rimmen Palace Crypts"]                = 669,
	["Rimmen Palace"]                       = 670,
	["Rimmen Palace Courtyard"]             = 671,
	["Dov-Vahl Shrine"]                     = 672,
	["Sepulcher of Mischance"]              = 673,
	["Shadow Dance Temple"]                 = 674,
	["Vault of Heavenly Scourge"]           = 675,
	["Moon Gate of Anequina"]               = 676,
	["Jode's Core"]                         = 677,
	["Darkpool Mine"]                       = 678,
	["The Tangle"]                          = 679,
	
		-- SOUTHERN ELSWEYR
	["Wind Scour Temple"]                   = 680,
	["Storm Talon Temple"]                  = 681,
	["Dark Water Temple"]                   = 682,
	["Vahlokzin's Domain"]                  = 683,
	["Vahlokzin's Lair"]                    = 684,
	["Senchal"]                             = 685,
	["Senchal Outlaws Refuge"]              = 686,
	["Senchal Palace"]                      = 687,
	["Southern Elsweyr"]                    = 688,
	["Tideholm"]                            = 689,
	["Dragonguard Sanctum"]                 = 690,
	["Moonlit Cove"]                        = 691,
	["Passage of Dad'na Ghaten"]            = 692,
	["Zazardi's Quarry and Mine"]           = 693,
	["Black Kiergo Arena"]                  = 694,
	["Forsaken Citadel"]                    = 695,
	["New Moon Fortress"]                   = 696,
	["Halls of the Highmane"]               = 697,
	["Path of Pride"]                       = 698,
	["Doomstone Keep"]                      = 699,
	["The Spilled Sand"]                    = 700,
	["Dragonhold"]                          = 701,
	["Jonelight Path"]                      = 702,

	-- WESTERN SKYRIM
	["Riften Ratway"]                       = 703,
	["Blackreach: Mzark Cavern"]            = 704,
	["Palace of Kings"]                     = 705,
	["Western Skyrim"]                      = 706,
	["Solitude"]                            = 707,
	["Kilkreath"]                           = 708,
	["Shadowgreen"]                         = 709,
	["Dragon Bridge Smuggler Caves"]        = 710,
	["Dragonhome"]                          = 711,
	["Mor Khazgur Mine"]                    = 712,
	["Chillwind Depths"]                    = 713,
	["Bleakridge Barrow"]                   = 714,
	["Red Eagle Ridge"]                     = 715,
	["Verglas Hollow"]                      = 716,
	["Frozen Coast"]                        = 717,
	["Morthal Barrow"]                      = 718,
	["Blackreach: Greymoor Caverns"]        = 719,
	["Kagnthamz"]                           = 720,
	["Tzinghalis"]                          = 721,
	["Lightless Hollow Mine"]               = 722,
	["Bthang Outpost"]                      = 723,
	["Blackreach: Dark Moon Grotto"]        = 724,
	["The Scraps"]                          = 725,
	["Might Barrow"]                        = 726,
	["The Undergrove"]                      = 727,
	["Greymoor Keep: West Wing"]            = 728,
	["Greymoor Keep"]                       = 729,
	["Gray Host Tunnels"]                   = 730,

	-- THE REACH
	["Gray Host Sanctuary"]                 = 731,
	["Grayhome"]                            = 732,
	["Castle Grayhome"]                     = 733,
	["Grayhome Ritual Chamber"]             = 734,
	["The Reach"]                           = 735,
	["Markarth"]                            = 736,
	["Understone Keep"]                     = 737,
	["Valthume"]                            = 738,
	["Reachwind Depths"]                    = 739,
	["Briar Rock Ruins"]                    = 740,
	["Briar Rock Crypts"]                   = 741,
	["Dead Crone Tower"]                    = 742,
	["Sanuarach Mine"]                      = 743,
	["Bthar-Zel"]                           = 744,
	["Bthar-Zel Bank"]                      = 745,
	["Bthar-Zel Vault"]                     = 746,
	["Lost Valley Redoubt"]                 = 747,
	["The Dark Descent"]                    = 748,
	["Gloomreach"]                          = 749,
	["Blackreach: Arkthzand"]               = 750,
	["Halls of Arkthzand"]                  = 751,
	["Nighthollow Keep"]                    = 752,
	["Chamber of the Dark Heart"]           = 753,
	["Nchuand-Zel"]                         = 754,
	["Arkthzand Orrery"]                    = 755,
	["Gray Haven"]                          = 756,
	
	-- Isle of Balfiera
	["Balfiera Ruins"]                      = 757,
	["Isle of Balfiera"]                    = 758,
	["Keywright's Gallery"]                 = 759,
	
		-- Blackwood
	["Imperial Cache Annex"]                = 760,
	["Ne Salas Cache Annex"]                = 761,
	["Imperial Sewers"]                     = 762,
	["Deadlands"]                           = 763,
	["Leyawiin"]                            = 764,
	["Blackwood"]                           = 765,
	["Undertow Cavern"]                     = 766,
	["Borderwatch Sewers"]                  = 767,
	["Borderwatch Courtyard"]               = 768,
	["Borderwatch Keep"]                    = 769,
	["Borderlands Crypt"]                   = 770,
	["Ayleid Ruins"]                        = 771,
	["Veyond"]                              = 772,
	["Deepscorn Hollow"]                    = 773,
	["Gideon"]                              = 774,
	["Twyllbek Ruins"]                      = 775,
	["Tidewater Cave"]                      = 776,
	["Glenbridge Xanmeer"]                  = 777,
	["Doomvault Porcixid"]                  = 778,
	["Xal Irasotl"]                         = 779,
	["Bloodrun Cave"]                       = 780,
	["Welke"]                               = 781,
	["Leyawiin Castle"]                     = 782,
	["Xi-Tsei"]                             = 783,
	["Stonewastes Keep"]                    = 784,
	["Doomvault Capraxus"]                  = 785,
	["Vandacia's Deadline Keep"]            = 786,
	["Ruction Ring"]                        = 787,
	["Vunalk1"]                             = 788,
	["Deadlands: The Ashen Forest"]         = 789,
	["White Gold Tower Throne Room"]        = 790,
	["Xynaa's Sanctuary"]                   = 791,
	["Arpenia"]                             = 792,
	["Doomvault Vulpinaz Upper level"]      = 793,
	["Doomvault Vulpinaz Mid Level"]        = 794,
	["Doomvault Vulpinaz Lower Level"]      = 795,
	["Anchor Chamber"]                      = 796,
	["Fort Redmane"]                        = 797,
}

-----------------------------------------
-- HELPER FUNCTIONS
-----------------------------------------

function Data:CollectMapIds()
	local sv = ZGV.sv.profile
	sv.mapids = {}

	for i = 0,1000 do
		local loczone, _ = _G.GetZoneInfo(i)
		sv.mapids[loczone] = i
	end
end
